# Generated by Django 3.2.16 on 2022-11-27 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='movie',
            constraint=models.UniqueConstraint(fields=('movie_title', 'director'), name='unique_movie_listing'),
        ),
    ]
